url: https://draescobarn.github.io


# Site settings
title: Dra. Estela Escobar Norzagaray
email: dra.escobarn@gmail.com
description: "Consultorio dental. Odontologia general, radiologia y endodoncia"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Anacleto Canabal 221-A
  - line: Villahermosa, Tabasco, 86190

# Build settings
markdown: kramdown
permalink: pretty
